custom_configuration.custom_configuration_add:
 route_name: custom_configuration.custom_configuration_add
 base_route: custom_configuration.admin_custom_config
 title: 'Add Custom Configuration setting'
custom_configuration.custom_list:
 route_name: custom_configuration.configuration_list
 base_route: custom_configuration.admin_custom_config
 title: 'Custom Configuration list'
