custom_configuration.redirect_config_form:
  title: 'Custom Configuration'
  route_name: custom_configuration.configuration_list
  parent: system.admin_config_system
  description: 'Manage custom configuration settings'
  weight: 8
