name: Custom Configuration
description: 'This will provide you a way to store multiple configuration.'
type: module

package: custom
# core: '8.x'
configure: custom_configuration.configuration_list

# Information added by Drupal.org packaging script on 2018-06-23
version: '8.x-1.2'
core: '8.x'
project: 'custom_configuration'
datestamp: 1529733826
